### ISSUE TITLE
Termux - Exit code = 135

### ISSUE THREAD

**Issue by randomguy273** [reisxd/revanced-builder#272]
**Describe the bug**
Can't build the YouTube ReVanced.

**To Reproduce**
Open the builder, select YouTube Revanced, Download the 17.32.35 version, Select all patches, wait to build and shows the error.

**Screenshots**
![20220819_220355](https://user-images.githubusercontent.com/110130703/185723537-896314ae-8009-4ff3-90c6-f755c4fb3164.jpg)

**ReVanced-Builder Version:**[3.2.3]

**Machine**

- OS: [Android]
- Version: [8.1.0]

**Additional context**
Termux from F-Droid fully updated, already tried to build mutiple times.

**Comment by reisxd** [comment]
Won't fix, because this issue occurs for no apparent reason.

**Comment by Alprnn357** [comment]
@reisxd @randomguy273 
I have the same problem but i found out that aapt2 program is actually broken. I was able to build yt revanced previously but now i completely reinstalled the builder and cannot build it.
https://github.com/rendiix/termux-aapt (armeabi-v7a)
tried to replace the aapt2 with new one i have given up there. It can pass the compiling rescources stage but still can't build with different error similiar to your screenshot.

**Comment by carls677** [comment]
solution to have the same version of youtube in play store

**Comment by reisxd** [comment]
> solution, to have the same version of youtube in play store

I don't get how could that be a solution, but alright...

**Comment by carls677** [comment]
> solution, to have the same version of youtube in play store

the microg and youtube revanced apk file is created, but youtube revanced says the app has stopped.

**Comment by shrihanDev** [comment]
The predictions are correct. The `aapt2` binary for `armeabi-v7a` is apparently broken due to, maybe, incompatible patches (see revanced/aapt2) and there's no bug fix currently. `aapt2` from other sources should, in theory, fail anyway since there are certain patches necessary for `aapt2` to work for patching YouTube.

The following patch (to revanced-builder) could be applied and checked if this works:
```patch
diff --git a/wsEvents/patchApp.js b/wsEvents/patchApp.js
index 5ba6bda..24accf0 100644
--- a/wsEvents/patchApp.js
+++ b/wsEvents/patchApp.js
@@ -180,6 +180,7 @@ module.exports = async function patchApp(ws) {
     global.jarNames.patchesJar,
     '-t',
     './revanced-cache',
+    '-r',
     '--experimental',
     '-a',
     `./revanced/${global.jarNames.selectedApp}.apk`,
```
How to apply:
```bash
$ cd ~/revanced-builder
$ patch -p1 wsEvents/patchApp.js
```
After that, paste the above patch code and then tap CTRL and then "D". Do it twice if needed. You should see `patching file wsEvents/patchApp.js` after doing that. Then, do `node .` and try to build if that works.

**Comment by reisxd** [comment]
@shrihanDev Most of the patches wouldn't work because they require resource patching.

**Comment by shrihanDev** [comment]
I know. That's why I said "try to build if that works".

**Comment by Alprnn357** [comment]
> The predictions are correct. The `aapt2` binary for `armeabi-v7a` is apparently broken due to, maybe, incompatible patches (see revanced/aapt2) and there's no bug fix currently. `aapt2` from other sources should, in theory, fail anyway since there are certain patches necessary for `aapt2` to work for patching YouTube.
> 
> The following patch (to revanced-builder) could be applied and checked if this works:
> 
> ```diff
> diff --git a/wsEvents/patchApp.js b/wsEvents/patchApp.js
> index 5ba6bda..24accf0 100644
> --- a/wsEvents/patchApp.js
> +++ b/wsEvents/patchApp.js
> @@ -180,6 +180,7 @@ module.exports = async function patchApp(ws) {
>      global.jarNames.patchesJar,
>      '-t',
>      './revanced-cache',
> +    '-r',
>      '--experimental',
>      '-a',
>      `./revanced/${global.jarNames.selectedApp}.apk`,
> ```
> 
> How to apply:
> 
> ```shell
> $ cd ~/revanced-builder
> $ patch -p1 wsEvents/patchApp.js
> ```
> 
> After that, paste the above patch code and then tap CTRL and then "D". Do it twice if needed. You should see `patching file wsEvents/patchApp.js` after doing that. Then, do `node .` and try to build if that works.

![Screenshot_20220911-211708_Chrome](https://user-images.githubusercontent.com/37711793/189542926-3a68c00f-5b35-4c34-ac8a-459fd9379db5.jpg)

You can see it worked without patching resources.

Log:
`[builder] INFO: Only decoding AndroidManifest.xml because resource patching is disabled
[builder] INFO: Reading dex files
[builder] INFO: Merging ./revanced/revanced-integrations-v0.36.6.apk
[builder] WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
[builder] WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
[builder] WARNING: Skipping minimized-playback-music, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping tasteBuilder-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping hide-get-premium, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] INFO: Skipping compact-header, reason: excluded by default
[builder] WARNING: Skipping upgrade-button-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping background-play, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-microg-support, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping codecs-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping exclusive-audio-playback, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp
[builder] WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] INFO: Skipping swipe-controls, reason: manually excluded
[builder] INFO: Skipping downloads, reason: manually excluded
[builder] INFO: Skipping seekbar-tapping, reason: manually excluded
[builder] WARNING: Skipping amoled, reason: deprecated: Theme patch already includes the Amoled theme.
[builder] WARNING: Either use theme instead or include it manually
[builder] INFO: Skipping disable-create-button, reason: manually excluded
[builder] INFO: Skipping return-youtube-dislike, reason: manually excluded
[builder] INFO: Skipping hide-autoplay-button, reason: manually excluded
[builder] INFO: Skipping premium-heading, reason: manually excluded
[builder] INFO: Skipping custom-branding, reason: manually excluded
[builder] INFO: Skipping disable-fullscreen-panels, reason: manually excluded
[builder] INFO: Skipping old-quality-layout, reason: manually excluded
[builder] INFO: Skipping theme, reason: manually excluded
[builder] INFO: Skipping hide-shorts-button, reason: manually excluded
[builder] INFO: Skipping hide-watermark, reason: manually excluded
[builder] INFO: Skipping sponsorblock, reason: manually excluded
[builder] INFO: Skipping enable-wide-searchbar, reason: manually excluded
[builder] INFO: Skipping tablet-mini-player, reason: manually excluded
[builder] INFO: Skipping minimized-playback, reason: manually excluded
[builder] INFO: Skipping custom-video-buffer, reason: manually excluded
[builder] INFO: Skipping always-autorepeat, reason: manually excluded
[builder] INFO: Skipping settings, reason: manually excluded
[builder] INFO: Skipping enable-debugging, reason: manually excluded
[builder] INFO: Skipping custom-playback-speed, reason: manually excluded
[builder] INFO: Skipping hdr-auto-brightness, reason: manually excluded
[builder] INFO: Skipping remember-video-quality, reason: manually excluded
[builder] INFO: Skipping video-ads, reason: manually excluded
[builder] INFO: Skipping general-ads, reason: manually excluded
[builder] INFO: Skipping hide-infocard-suggestions, reason: manually excluded
[builder] SEVERE: hide-cast-button failed:
[builder] app.revanced.patcher.patch.PatchResultError: 'hide-cast-button' depends on 'settings' but the following error was raised: 'settings' depends on 'settings-resource-patch' but the following error was raised: 'settings-resource-patch' depends on 'locale-config-fix' but the following error was raised: 'locale-config-fix' is a resource patch, but resource patching is disabled
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:298) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] INFO: client-spoof succeeded
[builder] SEVERE: microg-support failed: app.revanced.patcher.patch.PatchResultError: 'microg-support' depends on 'microg-resource-patch' but the following error was raised: 'microg-resource-patch' depends on 'locale-config-fix' but the following error was raised: 'locale-config-fix' is a resource patch, but resource patching is disabled
[builder] at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:298) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] INFO: Writing modified dex files
[builder] INFO: Writing dex file classes2.dex
[builder] INFO: Writing dex file classes3.dex
[builder] INFO: Writing dex file classes4.dex
[builder] INFO: Writing dex file classes.dex
[builder] INFO: Writing dex file classes5.dex
[builder] INFO: Writing dex file classes7.dex
[builder] INFO: Writing dex file classes6.dex
[builder] INFO: Writing dex file classes8.dex
[builder] INFO: Aligning revanced_raw.apk to revanced_aligned.apk
[builder] INFO: Signing revanced_aligned.apk to revanced_signed.apk
[builder] INFO: Copying revanced_signed.apk to revanced.apk
[builder] INFO: Finished
[builder] Copied files over to /storage/emulated/0/! Please install ReVanced, its located in /storage/emulated/0/ReVanced-YouTube-v17.33.42-armeabi-v7a-cli_v2.10.1-patches_v2.52.1.apk and if you are building YT/YTM ReVanced without root, also install /storage/emulated/0/microg.apk.`
