### ISSUE TITLE
revanced crashes on startup (root version)

### ISSUE THREAD

**Issue by Crolee** [reisxd/revanced-builder#415]
youtube revanced crashes on startup on version 17.35.35 
I was using the revanced builder using termux on Android and selected the root version.

**Comment by reisxd** [comment]
Downgrade to 17.33.35.

**Comment by Crolee** [comment]
how do i do that?

**Comment by shrihanDev** [comment]
> how do I do that?

Uninstall YT. Run builder again and select version 17.33.35.

**Comment by Crolee** [comment]
i then get this error after pressing "no" at the use already downloaded apk message
![Uploading Screenshot_20220914-160247.png…]()

**Comment by shrihanDev** [comment]
Actually, when I told you to uninstall YT, I meant uninstall the stock app. Since your stock is on an unsupported version, ReVanced cannot run on top of it. So either:

1. Open a root file manager and delete `/data/adb/service.d/mount_revanced_com.google.android.youtube.sh`.
2. Also delete `/data/adb/revanced`.
3. Wait for ReVanced upstream to support it and mark it as recommended.

Or:
1. Uninstall YT stock app.
2. Install YouTube version 17.33.35.
3. Use ReVanced Builder to build the same version.
