### ISSUE TITLE
Revanced builder 3.4.7 is saving all files to C drive

### ISSUE THREAD

**Issue by Vucko130** [reisxd/revanced-builder#460]
Revanced builder 3.4.7 is saving all files to C:\Users\user name\AppData\Roaming\IDM

It's happening in 3.4.7 but was fine in 3.4.5

**Comment by reisxd** [comment]
Is Buider inside the Downloads folder?

**Comment by shrihanDev** [comment]
That folder supposedly is the download location for Internet Download Manager. If you used it to download `revanced-builder-windows.exe`, and launched it then and there, it will be saved to IDM/revanced since Builder saves everything to a folder called revanced **in the location where the binary is there**.

Solution: Move (or copy) the binary to the preferred location and run from there.

**Comment by Vucko130** [comment]
revanced-builder-windows.exe is located and launched in D drive but it is saving all of it's files to C drive. It's using IDM's folder in appdata/roaming. That was not the case till 3.4.5.

**Comment by reisxd** [comment]
> revanced-builder-windows.exe is located and launched from the D drive, it should save all of its files from where it is launched as I got its own folder but it is saving all of its files to the C drive. It's using IDM's folder in AppData/roaming. That was not the case till 3.4.5.

Maybe it's missing write permisson, when I sometimes tried to install a module using npm without initializing, it'd error because it would try to write to the root of the disk and fail because theres no write permission.

Builder does not have any written code to do this sort of behaviour, maybe it uses the WINAPI to get the first folder it has R/W access to it? No idea, just a guess.

**Comment by shrihanDev** [comment]
I've tried to fix in 0849f5b91511e332aca9a804c036afcf4ab95f64. Could be unrelated, could be not. Could be fixed, could be not. I can't reproduce this.

**Comment by Vucko130** [comment]
> > revanced-builder-windows.exe is located and launched from the D drive, it should save all of its files from where it is launched as I got its own folder but it is saving all of its files to the C drive. It's using IDM's folder in AppData/roaming. That was not the case till 3.4.5.
> 
> Maybe it's missing write permisson, when I sometimes tried to install a module using npm without initializing, it'd error because it would try to write to the root of the disk and fail because theres no write permission.
> 
> Builder does not have any written code to do this sort of behaviour, maybe it uses the WINAPI to get the first folder it has R/W access to it? No idea, just a guess.
> 
> Edit: Try launching ReVanced Builder as admin, maybe it'll fix it...?

you're right. just tried running it with admin privilege. That fixed the problem. but without admin it's broken the same way I reported.
