### ISSUE TITLE
Revanced Builder on Android Failing in the patching step

### ISSUE THREAD

**Issue by berndt-toast83** [reisxd/revanced-builder#496]
Using the latest revanced builder on Android steps from your wiki, the following error is occurring during the patching step:

[builder] Exception in thread "main"
[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:519) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20) at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ... 22 more

Termux installed from F-Droid
Android 13 October 2022 update

**Comment by Mythodix** [comment]
I'm getting a similar error on PC

**Comment by Vacbo** [comment]
I'm also getting this error.

[builder] Exception in thread "main"
[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch
[builder] at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[builder] at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
[builder] at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20) at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134)
[builder] at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
[builder] at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch
[builder] at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 22 more

**Comment by ImAgoodGirlSumtimz** [comment]
I'm also getting the same error at the start of the patching process. I was patching YouTube v17.38.36 running Android 13 on a Google Pixel 6 Pro.

**Comment by Chaosrender** [comment]
My error

![Revanced issue](https://user-images.githubusercontent.com/115124747/194192248-9d247d2c-f25c-4c4e-bb58-1f59f4c8df7c.png)

**Comment by 1Phase1** [comment]
Can confirm, I'm getting the same error here.

 [builder] Exception in thread "main"
[builder] java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:519) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20) at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ... 22 more

**Comment by reisxd** [comment]
Not an issue with Builder.

**Comment by 0xShadx0** [comment]
If the issue isn't with Builder is there a way to work around that? Or is the issue with ReVanced itself?

**Comment by reisxd** [comment]
> If the issue isn't with Builder is there a way to work around that? Or is the issue with ReVanced itself?

It's with ReVanced itself, their patches are broken in CLI.
