### ISSUE TITLE
Video ads failed :(

### ISSUE THREAD

**Issue by B0TRICK** [reisxd/revanced-builder#515]
![Screenshot_20221021-111034_Brave](https://user-images.githubusercontent.com/113281799/197123143-ccbfc200-7367-4cb6-bd43-d056250fad3b.png)
 
After updating it is not working 😞

**Comment by reisxd** [comment]
Not an issue with Builder.

**Comment by muralivijay** [comment]
@B0TRICK don,t patch with latest version 17.40.XX . use 17.36.37 version video patch successed without any error

**Comment by B0TRICK** [comment]
Thank you so much for your help :)

**Comment by Retardium** [comment]
@reisxd 
I've the same problem with your builder. 
Patching v17.36.37 works fine but v17.40.41 fails. 

I've opened an issue at the revanced-patches repo but maintainer closed it since it's no official build tool and the wrong version (of YT I guess).
https://github.com/revanced/revanced-patches/issues/844

So is it a problem with your builder? 
Because v17.40.41 is marked as recommended in your script. :-)

**Comment by reisxd** [comment]
> @reisxd 
> I've the same problem with your builder. 
> Patching v17.36.37 works fine but v17.40.41 fails. 
> 
> I've opened an issue at the revanced-patches repo but maintainer closed it since it's no official build tool and the wrong version (of YT I guess).
> https://github.com/revanced/revanced-patches/issues/844
> 
> So is it a problem with your builder? 
> Because v17.40.41 is marked as recommended in your script. :-) 

A patch is targetting 17.40.41, which causes Builder to mark it as recommended.

**Comment by dimon222** [comment]
https://github.com/revanced/revanced-patches/pull/878#issuecomment-1294273551
