### ISSUE TITLE
Add Twitch in the app selection

### ISSUE THREAD

**Issue by PandoraPandorita** [reisxd/revanced-builder#549]
**Describe the bug**
A whole bunch of apps has been added since the last update that added applications to the builder happened, and one of them that can be downloaded from apkmirror is Twitch.

~~**To Reproduce**~~
~~Steps to reproduce the behavior:~~

~~1. Go to 'app selector'~~

~~**revanced-builder Version:** 3.4.16~~

~~**Desktop (please complete the following information):**~~

~~- OS: Arch Linux~~
~~- Version: guhh~~

~~**Additional context**~~
~~Add any other context about the problem here.~~

Unnecessary :troll: — shrihanDev

**Comment by CrowTaker** [comment]
Here you go, Twitch : #551

Currently, we have to manually add support for each app and it only works if it is available at APKMirror. For eg :- Nyx Music Player is not available. 

The code could be refactored to allow "technical" users to directly add new apps instead of waiting for an official update. 

As for the APKMirror scenario, the user can get the apk after installing from Play Store/trusted source.
