### ISSUE TITLE
**Non-recommended version selected**

### ISSUE THREAD

**Issue by Broukmiken** [reisxd/revanced-builder#681]
Hello,
No recommanded version (yt 18.05.40 for real) appears in the list given
the oldest that appears is 18.08.35.
So, we can't find the recommanded version.
i tryed many web browsers and Computers and it's the same issue.
can you have a look on it or give me an advice ?
thanks

**Comment by imaperson1060** [comment]
Just get the apk from

**Comment by imaperson1060** [comment]
No. The way the selection screen works is it looks at the most recent releases (first page of results) of YT on ApkMirror, and lists them. Unless the code is updated to scrape multiple pages. A useful feature would be a button at the bottom to "View more releases" and linking to the ApkMirror page.

**Comment by Grod56** [comment]
I really don't get the point of just listing the most recent apks regardless of whether recommended version is available or not. It just seems like a recipe for bugs down the line, as I'm sure a decent number of people would just select a random version instead of scouring the internet for the recommended apk. Previous versions used to include the recommended version, I don't know why that feature was removed in more recent iterations of this app.

**Comment by imaperson1060** [comment]
Because the patches weren't updated for so long the recommended version doesn't appear on the first page of results on ApkMirror. The feature actually wasn't changed at all. And the app throws a warning when you try to use an unrecommended version. If you feel that strongly, make a pull request for scraping multiple pages of results.

**Comment by Broukmiken** [comment]
@imaperson1060 
thank you for all thoses explanations.
it's not that hard to download ourself the good apk.
Perhaps next update will integrate like you said multiple pages of results.
Wait and see.

**Comment by imaperson1060** [comment]
I made a PR with the page navigation (#686). Hopefully it will be approved :)

**Comment by eixel05** [comment]
Hi, so I downloaded it from APKmirror, how do I tell revanced-builder to use it?
