### ISSUE TITLE
Youtube App Patch Failure

### ISSUE THREAD

**Issue by mecha-mann** [reisxd/revanced-builder#697]
[builder] An error occured:Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENTat ChildProcess._handle.onexit (node:internal/child_process:283:19)at onErrorNT (node:internal/child_process:476:16)at process.processTicksAndRejections (node:internal/process/task_queues:82:21)Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

Edit : there's a workaround, Go inside **revanced-cache** folder and install the "revanced_signed.apk" into your android device.

**Comment by magerg** [comment]
I have exactly the same issue.
v3.9.1, Windows 10 Version 10.0.19045 Build 19045

**Comment by ankur-raikwar** [comment]
@mecha-mann @magerg

But, it build the apk you need, just locate **"revanced.apk"** in  revanced folder.
The problem is it not signed so you need to sign it before you can install. 

You can use this tool to sign apk : [APK Easy Tool](https://forum.xda-developers.com/t/discontinued-windows-apk-easy-tool-v1-60-2022-06-23.3333960/)

**Comment by Jorchking** [comment]
> 

I don't understand your comment. I have the same issue to the guy, and I always did the same process. This fails even uploading the youtube apk or selecting in the executable/browser dialog. I don't understand the error.

**Comment by mecha-mann** [comment]
Yes, there's actually a folder named "revanced-cache". Go inside it and just install the "revanced_signed.apk" into your android device. Worked for me 👍
