### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Domnic79** [reisxd/revanced-builder#699]
**Describe the bug**
Cannot build vanced apk.

**To Reproduce**
 An error occured:Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**revanced-builder Version:** [3.9.1]

**Desktop (please complete the following information):**

- OS: [Windows]
- Version: [10]

**Additional context**

**Comment by Flyerone** [comment]
Duplicate error on same OS and revanced-builder version but with the twitter apk.

**Comment by benji78** [comment]
I had the same error, but it turns out (for me at least) that this error occurred right after the console said "[Builder] Finished" (or something along those lines). Which meant the apk was built but is not yet renamed from `revanced.apk` to `ReVanced-YouTube-cli_v….apk`. I was therefore able to update with the `revanced.apk` and it worked flawlessly.
