### ISSUE TITLE
working apk exported, but builder displayed an error at the end

### ISSUE THREAD

**Issue by aparajitob** [reisxd/revanced-builder#721]
I was building a patched YouTube apk for an armv7 device with a base apk version 18.15.40. A revanced apk was created, and I managed to install it on my device. The app seems to be working as expected so far.

However, the builder displayed an error at the end and I am not sure what it is about. I'm sharing the information as requested:
```
[builder] An error occured: 
Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENT 
at ChildProcess._handle.onexit (node:internal/child_process:283:19) 
at onErrorNT (node:internal/child_process:476:16) 
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Please report this bug here: https://github.com/reisxd/revanced-builder/issues.
```

- Builder version: v3.9.1
- Desktop OS: Windows 10
- Android version: 8.1.0

**Comment by ruben-hude** [comment]
Got the same issye

**Comment by ruben-hude** [comment]
Got the same issue with Windows 11 and Android 13. Despite the error message, the app seems to work fine.

**Comment by Legitti** [comment]
Same issue here!

**Comment by ayieko168** [comment]
Same issue:

> An error occured:
Error: spawn C:\snapshot\revanced-builder\node_modules\process-exists\node_modules\ps-list\fastlist.exe ENOENTat ChildProcess._handle.onexit (node:internal/child_process:283:19)at onErrorNT (node:internal/child_process:476:16)at process.processTicksAndRejections (node:internal/process/task_queues:82:21)Please report this bug here: https://github.com/reisxd/revanced-builder/issues.

**Comment by DShip91** [comment]
I'm having the exact same issue and it seems like a lot of other people are too considering how many times this has been reposted.
